2.4 routing
fedorenksei/eCommerce-Application pull request #7
Opened 2023-08-09 19:56 UTC by color-zebra

## Task

[Sprint #2](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint%232.md)

[Trello card](https://trello.com/c/tQZkjmjD)

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐞 Bug Fix
- [ ] 🎨 Style
- [ ] 👨‍💻 Code Refactor
- [ ] ✅ Test
- [ ] 📝 Documentation Update
- [ ] 🛠 Config
- [ ] ✨ Optimization
- [ ] 🤷‍♂️ Other: ...

## Description

Add basic routing for pages (Main, Login, Authorization).

[react-router](https://reactrouter.com/en/main)

## Todo

After implementing Registration and Login components logic, add redirecting.

## Related issues

none

## Added tests?

- [x] ✅ Yes
- [ ] 🙅‍♂️ No, they aren't needed
- [ ] 🙋‍♂️ No, because I need help

## Added to Storybook?

- [ ] ✅ Yes
- [x] 🙅‍♂️ No, they aren't needed
- [ ] 🙋‍♂️ No, because I need help

## Added to documentation?

- [ ] 📝 Yes, in README.md
- [x] 🙅‍♂️ No documentation needed

# Code Checklist:

- [x] KISS
- [x] DRY
- [x] YAGNI
- [x] Style guidelines
- [x] Documentation guidelines
- [x] I have performed a self-review of my code
- [x] I have added comments in hard-to-understand areas (if there are any)
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2023-08-09 21:55 UTC, fedorenksei reviewed
Попробовал быстренько вникнуть, появились вопросы (пардон, если глупые). 
Если есть ссылки на более конкретные статьи о той архитектуре, которую ты реализовал, приложи их, пожалуйста. 
Например, в [туториале](https://reactrouter.com/en/main/start/tutorial) описана какая-то немного другая реализация: в ней используется `createBrowserRouter`, а у нас этого не нашел. Надо ли будет это потом добавить? Или ты использовал просто какой-то альтернативный подход?

Точно ли здесь не нужны тест и story? Или их заморочно реализовать?

Будет ли роутинг связан с какими-то еще частями, например формами? Я подумал о том, что при отправке формы должны происходить и ее обработка, и изменение адреса — есть ли понимание, как это будет происходить?

2023-08-10 04:02 UTC, Nickbis approved these changes
Viewed. Everything is fine. Dealt with questions along the way.

2023-08-10 05:58 UTC, Margaryta-Maletz requested changes
Отличная работа и правильно написанный тест, но...
У меня замечания по форматированию. Чем раньше определитесь и настроите - тем проще будет в дальнейшем.

Хочется также отметить замечательные объяснения по каждому возникшему вопросу.

По вопросу о  Router могу сказать только, что выбранная версия "react-router-dom": "^6.14.2" актуальная на сегодня и для вас вполне достаточно стандартного BrowserRouter. Не вижу смысла усложнять сейчас. Знаю, что были серьзные изменения при переходе с 5 на 6 версию, но тут у вас все в порядке.

2023-08-10 07:16 UTC, fedorenksei approved these changes

2023-08-10 08:51 UTC, Margaryta-Maletz approved these changes

2023-08-10 08:56 UTC, merged